[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[env]

[build]
rustflags = [
	  "-C", "link-arg=-nostartfiles",
]
target = "xtensa-esp32s3-none-elf"

# [source.crates-io]
# replace-with = "vendored-sources"

# [source."git+https://gitlab.com/jD91mZM2/no-std-compat.git"]
# git = "https://gitlab.com/jD91mZM2/no-std-compat.git"
# replace-with = "vendored-sources"

# [source.vendored-sources]
# directory = "Bootloader/vendor"

[unstable]
build-std = ["alloc", "core"]
