name: Rust

on:
  push:
    branches: [ "Documentation", "Bootloader" ]
  pull_request:
    branches: [ "Documentation", "Bootloader" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: Bootloader

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
